server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_db
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB